import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import streamlit as st

import config
from src.answer_generator import generate_answer
from src.embedder import Embedder
from src.guardrails import check_query
from src.index_bootstrap import ensure_index
from src.retriever import Retriever
from src.vector_store import VectorStore

WELCOME = "Welcome to the HDFC Mutual Fund FAQ Assistant."
EXAMPLES = [
    "What is the expense ratio of HDFC Large Cap Fund?",
    "What is the lock-in period of the ELSS fund?",
    "How do I download my capital gains statement?",
]


@st.cache_resource
def load_retriever():
    return Retriever(Embedder(), ensure_index(VectorStore(), log=st.sidebar.info))


def answer_query(query):
    guard = check_query(query)
    if guard["action"] != "allow":
        return {"kind": "blocked", "action": guard["action"], "message": guard["message"], "link": guard["link"]}
    hits = load_retriever().retrieve(query)
    if not hits:
        return {"kind": "empty", "message": "Sorry, I could not find this in my sources. Please try another question."}
    return {"kind": "answered", "result": generate_answer(query, hits), "query": query}


def render(entry):
    if entry["kind"] == "answered":
        result = entry["result"]
        st.markdown(f"**Q:** {entry['query']}")
        st.markdown(f"**Assistant:** {result['answer']}")
        st.markdown(f"**Source:** [{result['citation_url']}]({result['citation_url']})")
        st.caption(
            f"{config.LAST_UPDATED_LABEL} {result['last_updated']} "
            f"(generated by: {result['generator']})"
        )
    elif entry["kind"] == "blocked":
        st.warning(entry["message"])
        if entry["link"]:
            st.markdown(f"[Learn more]({entry['link']})")
    else:
        st.warning(entry["message"])
    st.divider()


def use_example(text):
    st.session_state["query"] = text
    st.session_state["auto_ask"] = True


st.set_page_config(page_title="HDFC MF FAQ Assistant", page_icon=":bank:")
st.title("HDFC Mutual Fund FAQ Assistant")
st.write(WELCOME)
st.caption(config.DISCLAIMER)

with st.sidebar:
    st.subheader("Corpus")
    st.write(f"{len(config.SCHEMES)} HDFC scheme pages · top-{config.TOP_K} retrieval")
    st.caption(f"Embeddings: {config.EMBEDDING_MODEL} · ChromaDB `{config.CHROMA_COLLECTION}` (cosine)")
    st.caption(f"Answer model: {config.GROQ_MODEL} if a key is configured, else extractive fallback")
    with st.expander("Disclaimer"):
        st.write(config.DISCLAIMER_LONG)

st.write("Try an example:")
cols = st.columns(3)
for col, ex in zip(cols, EXAMPLES):
    col.button(ex, use_container_width=True, on_click=use_example, args=(ex,))

with st.form("ask_form"):
    query = st.text_input("Your question", key="query", placeholder="e.g. What is the exit load of HDFC Flexi Cap?")
    submitted = st.form_submit_button("Ask")

if submitted:
    st.session_state["auto_ask"] = False

typed = (st.session_state.get("query") or "").strip()
should_ask = bool(submitted and typed) or (st.session_state.get("auto_ask") and typed)

if should_ask:
    st.session_state["auto_ask"] = False
    with st.spinner("Retrieving from official sources (first query loads the embedding model, ~20s)..."):
        entry = answer_query(typed)
    st.session_state.setdefault("history", []).insert(0, entry)

if st.session_state.get("history"):
    st.caption("Answers above · " + config.DISCLAIMER)
    for entry in st.session_state["history"]:
        render(entry)
