import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import streamlit as st

import config
from src.answer_generator import generate_answer
from src.embedder import Embedder
from src.guardrails import check_query
from src.retriever import Retriever
from src.vector_store import VectorStore

WELCOME = "Welcome to the HDFC Mutual Fund FAQ Assistant."
EXAMPLES = [
    "What is the expense ratio of HDFC Large Cap Fund?",
    "What is the lock-in period of the ELSS fund?",
    "How do I download my capital gains statement?",
]


@st.cache_resource
def load_retriever():
    return Retriever(Embedder(), VectorStore())


st.set_page_config(page_title="HDFC MF FAQ Assistant", page_icon=":bank:")
st.title("HDFC Mutual Fund FAQ Assistant")
st.write(WELCOME)
st.caption(config.DISCLAIMER)

with st.expander("Disclaimer"):
    st.write(config.DISCLAIMER_LONG)

st.write("Try an example:")
cols = st.columns(3)
clicked = None
for col, ex in zip(cols, EXAMPLES):
    if col.button(ex, use_container_width=True):
        clicked = ex

query = st.text_input("Your question", value=clicked or "")

if st.button("Ask") and query.strip():
    with st.spinner("Retrieving from official sources..."):
        guard = check_query(query)
        if guard["action"] == "allow":
            hits = load_retriever().retrieve(query)
            if hits:
                result = generate_answer(query, hits)
                st.markdown(f"**Assistant:** {result['answer']}")
                st.markdown(f"**Source:** [{result['citation_url']}]({result['citation_url']})")
                st.caption(
                    f"{config.LAST_UPDATED_LABEL} {result['last_updated']} "
                    f"(generated by: {result['generator']})"
                )
            else:
                st.warning("Sorry, I could not find this in my sources. Please try another question.")
        else:
            st.warning(guard["message"])
            if guard["link"]:
                st.markdown(f"[Learn more]({guard['link']})")
