"""Phase 6: generate the sample Q&A deliverable (PRD 9.4) from the live pipeline.

Runs the same guardrail -> retrieve -> answer path as the CLI/Streamlit apps and
writes doc/sample_qa.md + doc/sample_qa.csv, so the published answers are real
outputs with their citation and supporting chunk ids, not hand-written text.
"""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import config
from src.answer_generator import generate_answer
from src.demo_cases import SAMPLE_QA_CASES
from src.embedder import Embedder
from src.guardrails import check_query
from src.retriever import Retriever
from src.vector_store import VectorStore

MD_PATH = config.PROJECT_ROOT / "doc" / "sample_qa.md"
CSV_PATH = config.PROJECT_ROOT / "doc" / "sample_qa.csv"
CSV_FIELDS = ["n", "query", "action", "answer", "citation_url", "last_updated", "context_chunk_ids"]


def run_case(case, retriever):
    guard = check_query(case["query"])
    if guard["action"] != "allow":
        return {
            "query": case["query"],
            "action": guard["action"],
            "answer": guard["message"],
            "citation_url": guard["link"] or "",
            "last_updated": "",
            "context_chunk_ids": "",
            "generator": "guardrail",
        }
    hits = retriever.retrieve(case["query"])
    if not hits:
        return {
            "query": case["query"],
            "action": "no_context",
            "answer": "Sorry, I could not find this in my sources. Please try another question.",
            "citation_url": "",
            "last_updated": "",
            "context_chunk_ids": "",
            "generator": "none",
        }
    result = generate_answer(case["query"], hits)
    result["query"] = case["query"]
    result["action"] = "answered"
    result["context_chunk_ids"] = ", ".join(h["chunk_id"] for h in hits)
    return result


def write_md(results):
    generated = sorted({r["generator"] for r in results})
    lines = [
        "# Sample Q&A",
        "",
        "Generated by `python scripts/build_sample_qa.py` from the live pipeline "
        "(guardrails -> retrieval -> answer generation). "
        f"Answer generator(s) used: {', '.join(generated)}.",
        "",
        f"> {config.DISCLAIMER} {config.DISCLAIMER_LONG}",
        "",
    ]
    factual = [r for r in results if r["action"] == "answered"]
    refused = [r for r in results if r["action"] != "answered"]
    lines += [f"## Factual queries ({len(factual)})", ""]
    for i, r in enumerate(factual, start=1):
        lines += [
            f"### Q{i}. {r['query']}",
            "",
            f"**A:** {r['answer']}",
            "",
            f"- Source: {r['citation_url']}",
            f"- {config.LAST_UPDATED_LABEL} {r['last_updated']}",
            f"- Retrieved context: {r['context_chunk_ids']}",
            f"- Answer path: {r['generator']} (grounding {r.get('grounding', 0):.0%})",
            "",
        ]
    lines += [f"## Refused / redirected queries ({len(refused)})", ""]
    for i, r in enumerate(refused, start=1):
        link = f"- Link: {r['citation_url']}" if r["citation_url"] else "- Link: none"
        lines += [
            f"### R{i}. {r['query']}",
            "",
            f"**A:** {r['answer']}",
            "",
            f"- Handled by guardrail: `{r['action']}`",
            link,
            "",
        ]
    lines += [
        "## Notes",
        "",
        "- Citation links and the last-updated note come from chunk metadata, never from the LLM.",
        "- Refused queries are blocked at the guardrail stage, before any retrieval or generation.",
        "- `grounding` is the share of the answer's content words that also occur in the retrieved "
        f"context; answers below {config.MIN_ANSWER_GROUNDING:.0%} are rejected and regenerated "
        "extractively from the top chunk.",
        f"- Corpus: {len(config.SCHEMES)} scheme pages, {len(factual)} answered / "
        f"{len(refused)} blocked in this sample. See `doc/sources.md`.",
        "",
    ]
    MD_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_csv(results):
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS, extrasaction="ignore")
        writer.writeheader()
        for i, r in enumerate(results, start=1):
            writer.writerow({"n": i, **{k: r.get(k, "") for k in CSV_FIELDS if k != "n"}})


def main():
    retriever = Retriever(Embedder(), VectorStore())
    results = [run_case(case, retriever) for case in SAMPLE_QA_CASES]
    write_md(results)
    write_csv(results)
    print(f"Wrote {MD_PATH.relative_to(config.PROJECT_ROOT)}")
    print(f"Wrote {CSV_PATH.relative_to(config.PROJECT_ROOT)}")
    for r in results:
        print(f"  [{r['action']:<21}] {r['query']}")


if __name__ == "__main__":
    main()
